services:
  backend:
    build:
      context: ./coffee-shop-backend
      dockerfile: Dockerfile
    image: coffee-shop-backend:latest
    container_name: coffee-shop-backend
    ports:
      - "5001:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      DB_HOST: host.docker.internal
      DB_PORT: 3306
    env_file:
      - ./coffee-shop-backend/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  frontend:
    build:
      context: ./coffee-shop-frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: https://apicoffeeshop.vanct.id.vn/api
        VITE_SOCKET_URL: https://apicoffeeshop.vanct.id.vn
        VITE_GOOGLE_CLIENT_ID: 558672106762-iuplg0cpu94l7i698q55tflfspg501s2.apps.googleusercontent.com
    image: coffee-shop-frontend:latest
    container_name: coffee-shop-frontend
    ports:
      - "3000:80"
    restart: unless-stopped
    depends_on:
      - backend
